### ISSUE TITLE
veloren-voxygen crashed

### ISSUE THREAD

**Issue by Doomsdayrs** [flathub/net.veloren.airshipper#16]
[veloren-airshipper.log.txt](https://github.com/flathub/net.veloren.airshipper/files/10045425/veloren-airshipper.log.txt)

**Comment by Frinksy** [comment]
Thanks for the logs. Would you mind telling what window manager you are using?

**Comment by bronson** [comment]
I'm getting the same error launching under Silverblue. Gnome Shell, so I think that means the Mutter window manager.

**Comment by Frinksy** [comment]
There is an issue tracking this on the Veloren GitLab here: https://gitlab.com/veloren/veloren/-/issues/1662
I can reproduce your issue and I think I've identified it, but it's not yet fixed.

In the meantime, you'd probably get things working by either using and X11 session or using Flatseal to disable the wayland permission (to make it fallback to X11 if that's an option).

**Comment by bronson** [comment]
They updated the keyboard crate which, in theory, should be a fix.

**Comment by Frinksy** [comment]
I'll close this for now, as it should be fixed upstream. Feel free to mention if you're still having the issue and this can be reopened.

The workaround to disable using wayland should no longer be needed.
