### ISSUE TITLE
build for aarch64 as well

### ISSUE THREAD

**Issue by ruzko** [flathub/net.veloren.airshipper#18]
Would be cool to game Veloren on devices like the Pinebook Pro, or assorted Linux phones.

Could you add support for aarch64 to the flathub build of airshipper?

**Comment by Frinksy** [comment]
I hadn't realised aarch64 veloren builds were provided through airshipper already :smile: . Happy to add aarch64 to the flathub builds.
I don't have any aarch64 devices I can properly test on, so feel free to report any issues.

**Comment by ruzko** [comment]
Thank you @Frinksy, I'll let you know if anything pops up :)
