### ISSUE TITLE
Veloren graphics corrupted

### ISSUE THREAD

**Issue by devurandom** [flathub/net.veloren.airshipper#6]
When I start Veloren, (via Airshipper -> Play, latest version available there), the graphics of the Veloren window are completely garbled. It looks like this: ![image](https://user-images.githubusercontent.com/63082/144851951-4f53bb49-d4e8-4141-930b-2199e73183a7.png)

I am not sure which version of Veloren it is starting. (How can I find out? The version number in the changelog, 0.11.0 from 2021-09-11, seems to be way older than what is actually running.)

```
Operating System: Gentoo Linux 2.8
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.15.6 (64-bit)
Graphics Platform: Wayland
Processors: 8 × AMD Ryzen 5 2400G with Radeon Vega Graphics
Memory: 13,5 GiB of RAM
Graphics Processor: AMD Radeon Vega 11 Graphics
```

```
❯ flatpak info net.veloren.airshipper

Airshipper - Airshipper is the official launcher for Veloren.

          ID: net.veloren.airshipper
         Ref: app/net.veloren.airshipper/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.6.0
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 13.4 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: a3c4f2bcf0b5c6f23f0a6c25ce8c2c2203450c1a2b760bac0d06124dffecc146
      Parent: 607bdfc67981f291ec4b51255f1dca049278066d9395902c8944e17e65c509c1
     Subject: Update to version 0.6.0. (baf393e9)
        Date: 2021-10-18 22:16:24 +0000

❯ flatpak info org.freedesktop.Platform.GL.default//20.08

Mesa - Mesa - The 3D Graphics Library

          ID: org.freedesktop.Platform.GL.default
         Ref: runtime/org.freedesktop.Platform.GL.default/x86_64/20.08
        Arch: x86_64
      Branch: 20.08
     Version: 21.1.8
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 313.2 MB

      Commit: f596d0ba6c8c9af5ab8e95e9b27332077dc152ca994d79263b8bcbe4079cf9f6
      Parent: 990060f03b83f3a4aa55a1b0461b225b5cedaaa0a0a87d9282755b2eb9a27978
     Subject: Export org.freedesktop.Platform.GL.default
        Date: 2021-11-17 12:20:24 +0000
```

**Comment by devurandom** [comment]
The issue persists with today's version for Veloren.

**Comment by Frinksy** [comment]
Thanks for the report. The logs would be at `~/.var/app/net.veloren.airshipper/data/airshipper/profiles/default/userdata/voxygen/logs/` and should also contain the version of the game you're running (though this might not be useful since Airshipper should just keep you up to date with the latest nightly version anyways).

Have you tried running a Veloren binary directly? You can grab the latest nightly here: https://veloren.net/download-other/ 
I think it would help to know if it's an issue with the game or the flatpak, or something in between.
I also saw your other issue about upgrading the Flatpak Runtime, I hope to get to it soon.

**Comment by devurandom** [comment]
> Thanks for the report. The logs would be at `~/.var/app/net.veloren.airshipper/data/airshipper/profiles/default/userdata/voxygen/logs/` and should also contain the version of the game you're running (though this might not be useful since Airshipper should just keep you up to date with the latest nightly version anyways).

[2021-12-27_voxygen.log](https://github.com/flathub/net.veloren.airshipper/files/7779865/2021-12-27_voxygen.log)

> Have you tried running a Veloren binary directly? You can grab the latest nightly here: https://veloren.net/download-other/ I think it would help to know if it's an issue with the game or the flatpak, or something in between.

That works:

![image](https://user-images.githubusercontent.com/63082/147465773-63192984-1bc0-4ad7-9402-e476b6cdc568.png)

But the environment is very different from the standardised environment inside the Flatpak:

```
Operating System: Gentoo Linux 2.8
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.9-gentoo-dist (64-bit)
Graphics Platform: Wayland
Processors: 8 × AMD Ryzen 5 2400G with Radeon Vega Graphics
Memory: 13,5 GiB of RAM
Graphics Processor: AMD Radeon Vega 11 Graphics
```

(Mesa 21.3.1, Wayland 1.20.0, XWayland 21.1.4, libxcb 1.14, ...)

[vulkaninfo.log](https://github.com/flathub/net.veloren.airshipper/files/7779891/vulkaninfo.log)

> I also saw your other issue about upgrading the Flatpak Runtime, I hope to get to it soon.

Thanks!

**Comment by devurandom** [comment]
Sadly #7 did *not* solve this issue. Is there any way I can get more information about potential problems?

```
❯ flatpak info net.veloren.airshipper

Airshipper - Airshipper is the official launcher for Veloren.

          ID: net.veloren.airshipper
         Ref: app/net.veloren.airshipper/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.6.0
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 13.4 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 801a69f47b0543bb8bd183fb6ac7d45fa36fc4f69868ed26ce566a4abaeca73b
      Parent: a3c4f2bcf0b5c6f23f0a6c25ce8c2c2203450c1a2b760bac0d06124dffecc146
     Subject: Bump freedesktop.org to 21.08 (including rust) (c3f7cbca)
        Date: 2022-01-09 18:33:52 +0000
```
```
❯ flatpak info org.freedesktop.Platform

Freedesktop Platform - Shared libraries

          ID: org.freedesktop.Platform
         Ref: runtime/org.freedesktop.Platform/x86_64/21.08
        Arch: x86_64
      Branch: 21.08
     Version: 21.08.9
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 559.0 MB

      Commit: b27db466e56f7e49e794656b84153c8b81f929ca8b5b8400142b19bb48b9a63d
      Parent: 108f39d0653422812e69b53e8b6249f4a4e131a2147df7202cde70ee4e0a5742
     Subject: Export org.freedesktop.Platform
        Date: 2022-01-08 13:08:51 +0000
```
```
❯ flatpak info org.freedesktop.Platform.GL.default

Mesa - Mesa - The 3D Graphics Library

          ID: org.freedesktop.Platform.GL.default
         Ref: runtime/org.freedesktop.Platform.GL.default/x86_64/21.08
        Arch: x86_64
      Branch: 21.08
     Version: 21.3.3
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 387.2 MB

      Commit: 86a1c8526bda603bdfadaaa0c3c76a1afcebf75ad1706c25fee3160765650a13
      Parent: 7a5a0c7cd96e00abcef4a342244f10125892b70709f0d291864fde9399e8e6df
     Subject: Export org.freedesktop.Platform.GL.default
        Date: 2022-01-08 13:20:20 +0000
```
