### ISSUE TITLE
Update Flatpak Runtime to org.freedesktop.Platform//21.08

### ISSUE THREAD

**Issue by devurandom** [flathub/net.veloren.airshipper#7]
I would like to request updating the Flatpak Runtime to org.freedesktop.Platform//21.08, so I can get rid of the old 20.08 version that only very few Flatpaks still require.

My hope is that this would also resolve #6, as it implies updating to a newer version of the Mesa OpenGL and Vulkan implementation.

**Comment by Frinksy** [comment]
Closed with #4
